tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "openssl"
brew "composer"
brew "dnsmasq", restart_service: true
brew "ffmpeg"
brew "mackup"
brew "node"
brew "php", restart_service: true
brew "youtube-dl"
brew "zsh-completions"

cask "bettertouchtool"
cask "clion"
cask "discord"
cask "docker"
cask "dropbox"
cask "figma"
cask "firefox"
cask "gimp"
cask "gitkraken"
cask "google-chrome"
cask "intellij-idea"
cask "java"
cask "microsoft-office"
cask "phantomjs"
cask "phpstorm"
cask "postman"
cask "rider"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "tower"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "vyprvpn"
cask "webstorm"
